pipeline {
    agent none 

    stages {
        // Stage 1: Install
        stage('Install & Test') {
            agent {
                docker { 
                    image 'node:18-alpine' 
                    reuseNode true
                }
            }
            steps {
                dir('BravoScript') {
                    sh 'npm install'
                }
            }
        }

        // Stage 2: Build
        stage('Build Image') {
            agent any 
            steps {
                dir('BravoScript') {
                    sh "docker build -t bravoscript:${BUILD_NUMBER} ."
                }
            }
        }

        // Stage 3: Deploy (NEW)
        stage('Deploy') {
            agent any
            steps {
                script {
                    echo 'Deploying application...'
                    
                    // 1. Stop old container if it exists (|| true ignores errors if it doesn't exist)
                    sh 'docker stop bravoscript-app || true'
                    
                    // 2. Remove old container
                    sh 'docker rm bravoscript-app || true'
                    
                    // 3. Run the new version
                    // -d: Run in background
                    // -p 3000:3000: Map port 3000 on your laptop to 3000 in the container
                    // --name: Give it a fixed name so we can find it next time
                    sh "docker run -d -p 1234:1234 --name bravoscript-app bravoscript:${BUILD_NUMBER}"
                }
            }
        }
    }
}
