pipeline {
    agent none 

    stages {
        // Stage 1: Install & Test (Same as before)
        stage('Install & Test') {
            agent {
                docker { 
                    image 'node:18-alpine' 
                    reuseNode true
                }
            }
            steps {
                dir('BravoScript') {
                    sh 'npm install'
                    // sh 'npm test' 
                }
            }
        }

        // Stage 2: Build Docker Image (NEW)
        stage('Build Image') {
            agent any /* Uses your Jenkins container which has Docker CLI installed */
            
            steps {
                dir('BravoScript') {
                    echo 'Building Docker Image...'
                    /* We use ${BUILD_NUMBER} to give every build a unique ID */
                    sh "docker build -t bravoscript:${BUILD_NUMBER} ."
                }
            }
        }
    }
}
